In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('sonar.csv')
data=pd.read_csv('sonar.csv',names=range(0,61),header=0)

In [3]:
data=pd.DataFrame(data=data)
data

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039     NaN     NaN     NaN   

         58      59   60  
0    0.0090  0.0032  1.0  
1    0.0052  0.0044  1.0  
2    0.0095  0.0078  1.0  
3    0.0040  0.0117  1.0  
4    0.0107  0.0094  1.0  
..      ...     ...  ...  
203  0.0193  0.0157  0.0  
204  0.0062  0.0067  0.0  
205  0.0077  0.0031  0.0  
206  0.0036  0.0048  0.0  
207     NaN     NaN  NaN  

[208 rows x 61 columns]

In [4]:
df=data.dropna()
df

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0272  0.0378  0.0488  0.0848  0.1127  0.1103  0.1349  0.2337  0.3113   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   

         9   ...      51      52      53      54      55      56      57  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.3997  ...  0.0091  0.0045  0.0043  0.0043  0.0098  0.0054  0.0051   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   

         58      59   60  
0    0.0090  0.0032  1.0  
1    0.0052  0.0044  1.0  
2    0.0095  0.0078  1.0  
3    0.0040  0.0117  1.0  
4    0.0107  0.0094  1.0  
..      ...     ...  ...  
202  0.0065  0.0103  0.0  
203  0.0193  0.0157  0.0  
204  0.0062  0.0067  0.0  
205  0.0077  0.0031  0.0  
206  0.0036  0.0048  0.0  

[207 rows x 61 columns]

In [5]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [6]:
df.shape

(207, 61)

In [7]:
df.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
       ...   
56    float64
57    float64
58    float64
59    float64
60    float64
Length: 61, dtype: object

In [8]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [9]:
df.info

<bound method DataFrame.info of          0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0272  0.0378  0.0488  0.0848  0.1127  0.1103  0.1349  0.2337  0.3113   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   

         9   ...   

In [10]:
df.describe

<bound method NDFrame.describe of          0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0272  0.0378  0.0488  0.0848  0.1127  0.1103  0.1349  0.2337  0.3113   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   

         9   ... 

In [11]:
dfcor=df.corr()
dfcor

0         1         2         3         4         5         6   \
0   1.000000  0.735894  0.571897  0.491470  0.344952  0.238965  0.260743   
1   0.735894  1.000000  0.780850  0.606995  0.420327  0.333117  0.279319   
2   0.571897  0.780850  1.000000  0.781393  0.544500  0.343414  0.187617   
3   0.491470  0.606995  0.781393  1.000000  0.726481  0.350974  0.244593   
4   0.344952  0.420327  0.544500  0.726481  1.000000  0.594848  0.332568   
..       ...       ...       ...       ...       ...       ...       ...   
56  0.313630  0.280433  0.379268  0.339045  0.217015  0.158214  0.183971   
57  0.368104  0.353221  0.332405  0.343644  0.236430  0.200999  0.240422   
58  0.357011  0.352185  0.424639  0.419862  0.290305  0.219654  0.182669   
59  0.348591  0.359939  0.379214  0.404681  0.259587  0.185012  0.227881   
60 -0.272906 -0.232024 -0.196466 -0.253975 -0.227615 -0.138521 -0.119361   

          7         8         9   ...        51        52        53        54  \
0   0.355584  0.353474  0.318457  ...  0.355410  0.312024  0.322315  0.312012   
1   0.334641  0.316755  0.270875  ...  0.434606  0.346259  0.384377  0.380464   
2   0.238478  0.253277  0.220762  ...  0.395152  0.334680  0.365117  0.287662   
3   0.247112  0.247425  0.238545  ...  0.375305  0.366014  0.332686  0.283461   
4   0.204761  0.178564  0.184607  ...  0.267813  0.317241  0.202106  0.193609   
..       ...       ...       ...  ...       ...       ...       ...       ...   
56  0.267693  0.194341  0.141137  ...  0.191867  0.309592  0.359722  0.385716   
57  0.288121  0.232175  0.213190  ...  0.310425  0.372272  0.402483  0.502239   
58  0.194532  0.097391  0.058584  ...  0.298963  0.346699  0.446771  0.453293   
59  0.146273  0.095215  0.096626  ...  0.195263  0.280021  0.288791  0.269084   
60 -0.189440 -0.321890 -0.340982  ... -0.288717 -0.140797 -0.187285 -0.099431   

          55        56        57        58        59        60  
0   0.220479  0.313630  0.368104  0.357011  0.348591 -0.272906  
1   0.262237  0.280433  0.353221  0.352185  0.359939 -0.232024  
2   0.286775  0.379268  0.332405  0.424639  0.379214 -0.196466  
3   0.280224  0.339045  0.343644  0.419862  0.404681 -0.253975  
4   0.198101  0.217015  0.236430  0.290305  0.259587 -0.227615  
..       ...       ...       ...       ...       ...       ...  
56  0.514684  1.000000  0.508747  0.430889  0.291405 -0.003934  
57  0.463114  0.508747  1.000000  0.549985  0.334231 -0.187837  
58  0.430504  0.430889  0.549985  1.000000  0.645992 -0.132483  
59  0.352191  0.291405  0.334231  0.645992  1.000000 -0.085950  
60 -0.131336 -0.003934 -0.187837 -0.132483 -0.085950  1.000000  

[61 rows x 61 columns]

In [12]:
df.skew()

0     2.124331
1     2.149652
2     2.649075
3     3.394318
4     2.017464
        ...   
56    1.646175
57    2.091918
58    1.730285
59    2.798881
60    0.126773
Length: 61, dtype: float64

In [13]:
x=df.iloc[:,0:-1]
x.shape

(207, 60)

In [23]:
y=df.iloc[:,-1]
y.shape

(207,)

In [16]:
from sklearn.decomposition import PCA
pca=PCA(n_components=10)

In [17]:
x=pca.fit_transform(x)

In [18]:
x.shape

(207, 10)

In [24]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [25]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [26]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
x1=scale.fit_transform(x)

In [33]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
x1_train,x1_test,y_train,y_test=train_test_split(x1,y,test_size=.22,random_state=43)

In [34]:
lr=LogisticRegression()

In [35]:
lr.fit(x1_train,y_train)
lr.score(x1_train,y_train)
predlr=lr.predict(x1_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))

0.717391304347826
[[17  3]
 [10 16]]
              precision    recall  f1-score   support

           0       0.63      0.85      0.72        20
           1       0.84      0.62      0.71        26

    accuracy                           0.72        46
   macro avg       0.74      0.73      0.72        46
weighted avg       0.75      0.72      0.72        46



In [37]:
gnb= GaussianNB()
gnb.fit(x1_train,y_train)
gnb.score(x1_train,y_train)
predgnb=gnb.predict(x1_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

0.7391304347826086
[[17  3]
 [ 9 17]]
              precision    recall  f1-score   support

           0       0.65      0.85      0.74        20
           1       0.85      0.65      0.74        26

    accuracy                           0.74        46
   macro avg       0.75      0.75      0.74        46
weighted avg       0.76      0.74      0.74        46



In [38]:
model=[LogisticRegression(),GaussianNB(),DecisionTreeClassifier()]

In [40]:
for m in model:
    m.fit(x1_train,y_train)
    m.score(x1_train,y_train)
    predm=m.predict(x1_test)
    print('Accuracy score of',m,'is')
    print(accuracy_score(y_test,predm))
    print(confusion_matrix(y_test,predm))
    print(classification_report(y_test,predm))
    print('\n')

Accuracy score of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False) is
0.717391304347826
[[17  3]
 [10 16]]
              precision    recall  f1-score   support

           0       0.63      0.85      0.72        20
           1       0.84      0.62      0.71        26

    accuracy                           0.72        46
   macro avg       0.74      0.73      0.72        46
weighted avg       0.75      0.72      0.72        46



Accuracy score of GaussianNB(priors=None, var_smoothing=1e-09) is
0.7391304347826086
[[17  3]
 [ 9 17]]
              precision    recall  f1-score   support

           0       0.65      0.85      0.74        20
           1       0.85      0.65      0.74        26

    accuracy        

In [45]:
from sklearn.model_selection import cross_val_score

gnbscores = cross_val_score(gnb,x1,y,cv=5)
print(gnbscores)
print(gnbscores.mean(),gnbscores.std())

[0.47619048 0.76190476 0.3902439  0.70731707 0.3902439 ]
0.5451800232288038 0.15876271348736604


In [47]:
dt=DecisionTreeClassifier()

In [49]:
dt.fit(x1_train,y_train)
dt.score(x1_train,y_train)
preddt=dt.predict(x1_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))

0.7391304347826086
[[17  3]
 [ 9 17]]
              precision    recall  f1-score   support

           0       0.65      0.85      0.74        20
           1       0.85      0.65      0.74        26

    accuracy                           0.74        46
   macro avg       0.75      0.75      0.74        46
weighted avg       0.76      0.74      0.74        46



In [50]:
from sklearn.model_selection import cross_val_score

dtscores = cross_val_score(dt,x,y,cv=5)
print(dtscores)
print(dtscores.mean(),dtscores.std())

[0.38095238 0.52380952 0.53658537 0.65853659 0.34146341]
0.4882694541231126 0.11459265882740462


In [51]:
from sklearn.model_selection import cross_val_score

lrscores = cross_val_score(lr,x,y,cv=5)
print(lrscores)
print(lrscores.mean(),lrscores.std())

[0.45238095 0.9047619  0.56097561 0.85365854 0.43902439]
0.6421602787456446 0.19877749341783738


In [52]:
svc=SVC()

In [53]:
svc.fit(x1_train,y_train)
svc.score(x1_train,y_train)
predsvc=svc.predict(x1_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))

0.7391304347826086
[[17  3]
 [ 9 17]]
              precision    recall  f1-score   support

           0       0.65      0.85      0.74        20
           1       0.85      0.65      0.74        26

    accuracy                           0.74        46
   macro avg       0.75      0.75      0.74        46
weighted avg       0.76      0.74      0.74        46



In [54]:
from sklearn.model_selection import cross_val_score

svcscores = cross_val_score(svc,x,y,cv=5)
print(svcscores)
print(svcscores.mean(),svcscores.std())

[0.42857143 0.80952381 0.58536585 0.75609756 0.36585366]
0.589082462253194 0.1744116594207654
