In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv('titanic_train.csv')
data

Unnamed: 0  Unnamed: 0.1  PassengerId  Survived  Pclass  \
0             0             0            1         0       3   
1             1             1            2         1       1   
2             2             2            3         1       3   
3             3             3            4         1       1   
4             4             4            5         0       3   
..          ...           ...          ...       ...     ...   
886         886           886          887         0       2   
887         887           887          888         1       1   
888         888           888          889         0       3   
889         889           889          890         1       1   
890         890           890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 14 columns]

In [4]:
data.isnull().sum()

Unnamed: 0        0
Unnamed: 0.1      0
PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             177
SibSp             0
Parch             0
Ticket            0
Fare              0
Cabin           687
Embarked          2
dtype: int64

In [5]:
data['Age'].head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [6]:
data['Age'].mean()

29.69911764705882

In [7]:
import scipy
from scipy import stats
from scipy.stats import percentileofscore

In [8]:
data.describe()

Unnamed: 0  Unnamed: 0.1  PassengerId    Survived      Pclass  \
count  891.000000    891.000000   891.000000  891.000000  891.000000   
mean   445.000000    445.000000   446.000000    0.383838    2.308642   
std    257.353842    257.353842   257.353842    0.486592    0.836071   
min      0.000000      0.000000     1.000000    0.000000    1.000000   
25%    222.500000    222.500000   223.500000    0.000000    2.000000   
50%    445.000000    445.000000   446.000000    0.000000    3.000000   
75%    667.500000    667.500000   668.500000    1.000000    3.000000   
max    890.000000    890.000000   891.000000    1.000000    3.000000   

              Age       SibSp       Parch        Fare  
count  714.000000  891.000000  891.000000  891.000000  
mean    29.699118    0.523008    0.381594   32.204208  
std     14.526497    1.102743    0.806057   49.693429  
min      0.420000    0.000000    0.000000    0.000000  
25%     20.125000    0.000000    0.000000    7.910400  
50%     28.000000    0.000000    0.000000   14.454200  
75%     38.000000    1.000000    0.000000   31.000000  
max     80.000000    8.000000    6.000000  512.329200

In [9]:
data.isnull().sum()

Unnamed: 0        0
Unnamed: 0.1      0
PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             177
SibSp             0
Parch             0
Ticket            0
Fare              0
Cabin           687
Embarked          2
dtype: int64

In [10]:
data['Age'].head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [11]:
mean_val=data['Age'].mean()
mean_val

29.69911764705882

In [12]:
data['Age']=data['Age'].fillna(value=mean_val)

In [13]:
data['Age'].head(10)

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: Age, dtype: float64

In [14]:
data['Cabin'].head()

0     NaN
1     C85
2     NaN
3    C123
4     NaN
Name: Cabin, dtype: object

In [15]:
data=pd.read_csv('titanic_train.csv')
data

Unnamed: 0  Unnamed: 0.1  PassengerId  Survived  Pclass  \
0             0             0            1         0       3   
1             1             1            2         1       1   
2             2             2            3         1       3   
3             3             3            4         1       1   
4             4             4            5         0       3   
..          ...           ...          ...       ...     ...   
886         886           886          887         0       2   
887         887           887          888         1       1   
888         888           888          889         0       3   
889         889           889          890         1       1   
890         890           890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 14 columns]

In [16]:
data.dropna(axis=1,inplace=True)

In [17]:
data

Unnamed: 0  Unnamed: 0.1  PassengerId  Survived  Pclass  \
0             0             0            1         0       3   
1             1             1            2         1       1   
2             2             2            3         1       3   
3             3             3            4         1       1   
4             4             4            5         0       3   
..          ...           ...          ...       ...     ...   
886         886           886          887         0       2   
887         887           887          888         1       1   
888         888           888          889         0       3   
889         889           889          890         1       1   
890         890           890          891         0       3   

                                                  Name     Sex  SibSp  Parch  \
0                              Braund, Mr. Owen Harris    male      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                               Heikkinen, Miss. Laina  female      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                             Allen, Mr. William Henry    male      0      0   
..                                                 ...     ...    ...    ...   
886                              Montvila, Rev. Juozas    male      0      0   
887                       Graham, Miss. Margaret Edith  female      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female      1      2   
889                              Behr, Mr. Karl Howell    male      0      0   
890                                Dooley, Mr. Patrick    male      0      0   

               Ticket     Fare  
0           A/5 21171   7.2500  
1            PC 17599  71.2833  
2    STON/O2. 3101282   7.9250  
3              113803  53.1000  
4              373450   8.0500  
..                ...      ...  
886            211536  13.0000  
887            112053  30.0000  
888        W./C. 6607  23.4500  
889            111369  30.0000  
890            370376   7.7500  

[891 rows x 11 columns]

In [18]:
data.drop(['Ticket'],axis=1,inplace=True)

In [19]:
data.head(10)

Unnamed: 0  Unnamed: 0.1  PassengerId  Survived  Pclass  \
0           0             0            1         0       3   
1           1             1            2         1       1   
2           2             2            3         1       3   
3           3             3            4         1       1   
4           4             4            5         0       3   
5           5             5            6         0       3   
6           6             6            7         0       1   
7           7             7            8         0       3   
8           8             8            9         1       3   
9           9             9           10         1       2   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                             Heikkinen, Miss. Laina  female      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                           Allen, Mr. William Henry    male      0      0   
5                                   Moran, Mr. James    male      0      0   
6                            McCarthy, Mr. Timothy J    male      0      0   
7                     Palsson, Master. Gosta Leonard    male      3      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female      0      2   
9                Nasser, Mrs. Nicholas (Adele Achem)  female      1      0   

      Fare  
0   7.2500  
1  71.2833  
2   7.9250  
3  53.1000  
4   8.0500  
5   8.4583  
6  51.8625  
7  21.0750  
8  11.1333  
9  30.0708

In [20]:
data.drop(['Name'],axis=1,inplace=True)

In [21]:
data

Unnamed: 0  Unnamed: 0.1  PassengerId  Survived  Pclass     Sex  SibSp  \
0             0             0            1         0       3    male      1   
1             1             1            2         1       1  female      1   
2             2             2            3         1       3  female      0   
3             3             3            4         1       1  female      1   
4             4             4            5         0       3    male      0   
..          ...           ...          ...       ...     ...     ...    ...   
886         886           886          887         0       2    male      0   
887         887           887          888         1       1  female      0   
888         888           888          889         0       3  female      1   
889         889           889          890         1       1    male      0   
890         890           890          891         0       3    male      0   

     Parch     Fare  
0        0   7.2500  
1        0  71.2833  
2        0   7.9250  
3        0  53.1000  
4        0   8.0500  
..     ...      ...  
886      0  13.0000  
887      0  30.0000  
888      2  23.4500  
889      0  30.0000  
890      0   7.7500  

[891 rows x 9 columns]

In [22]:
data.drop(['PassengerId'],axis=1,inplace=True)
data

Unnamed: 0  Unnamed: 0.1  Survived  Pclass     Sex  SibSp  Parch     Fare
0             0             0         0       3    male      1      0   7.2500
1             1             1         1       1  female      1      0  71.2833
2             2             2         1       3  female      0      0   7.9250
3             3             3         1       1  female      1      0  53.1000
4             4             4         0       3    male      0      0   8.0500
..          ...           ...       ...     ...     ...    ...    ...      ...
886         886           886         0       2    male      0      0  13.0000
887         887           887         1       1  female      0      0  30.0000
888         888           888         0       3  female      1      2  23.4500
889         889           889         1       1    male      0      0  30.0000
890         890           890         0       3    male      0      0   7.7500

[891 rows x 8 columns]

In [23]:
data.drop(['Unnamed: 0'],axis=1,inplace=True)
data

Unnamed: 0.1  Survived  Pclass     Sex  SibSp  Parch     Fare
0               0         0       3    male      1      0   7.2500
1               1         1       1  female      1      0  71.2833
2               2         1       3  female      0      0   7.9250
3               3         1       1  female      1      0  53.1000
4               4         0       3    male      0      0   8.0500
..            ...       ...     ...     ...    ...    ...      ...
886           886         0       2    male      0      0  13.0000
887           887         1       1  female      0      0  30.0000
888           888         0       3  female      1      2  23.4500
889           889         1       1    male      0      0  30.0000
890           890         0       3    male      0      0   7.7500

[891 rows x 7 columns]

In [24]:
data.drop(['Unnamed: 0.1'],axis=1,inplace=True)
data

Survived  Pclass     Sex  SibSp  Parch     Fare
0           0       3    male      1      0   7.2500
1           1       1  female      1      0  71.2833
2           1       3  female      0      0   7.9250
3           1       1  female      1      0  53.1000
4           0       3    male      0      0   8.0500
..        ...     ...     ...    ...    ...      ...
886         0       2    male      0      0  13.0000
887         1       1  female      0      0  30.0000
888         0       3  female      1      2  23.4500
889         1       1    male      0      0  30.0000
890         0       3    male      0      0   7.7500

[891 rows x 6 columns]

In [25]:
data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [26]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [27]:
pd.get_dummies(data['Sex']).head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [28]:
data

Survived  Pclass     Sex  SibSp  Parch     Fare
0           0       3    male      1      0   7.2500
1           1       1  female      1      0  71.2833
2           1       3  female      0      0   7.9250
3           1       1  female      1      0  53.1000
4           0       3    male      0      0   8.0500
..        ...     ...     ...    ...    ...      ...
886         0       2    male      0      0  13.0000
887         1       1  female      0      0  30.0000
888         0       3  female      1      2  23.4500
889         1       1    male      0      0  30.0000
890         0       3    male      0      0   7.7500

[891 rows x 6 columns]

In [29]:
pd.get_dummies(data['Sex'])

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [30]:
data

Survived  Pclass     Sex  SibSp  Parch     Fare
0           0       3    male      1      0   7.2500
1           1       1  female      1      0  71.2833
2           1       3  female      0      0   7.9250
3           1       1  female      1      0  53.1000
4           0       3    male      0      0   8.0500
..        ...     ...     ...    ...    ...      ...
886         0       2    male      0      0  13.0000
887         1       1  female      0      0  30.0000
888         0       3  female      1      2  23.4500
889         1       1    male      0      0  30.0000
890         0       3    male      0      0   7.7500

[891 rows x 6 columns]

In [31]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.pairplot(data)
plt.show()

<Figure size 1250x1250 with 30 Axes>

In [32]:
data.skew()

Survived    0.478523
Pclass     -0.630548
SibSp       3.695352
Parch       2.749117
Fare        4.787317
dtype: float64

In [33]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

data['Sex'] = le.fit_transform(data['Sex'])
data

Survived  Pclass  Sex  SibSp  Parch     Fare
0           0       3    1      1      0   7.2500
1           1       1    0      1      0  71.2833
2           1       3    0      0      0   7.9250
3           1       1    0      1      0  53.1000
4           0       3    1      0      0   8.0500
..        ...     ...  ...    ...    ...      ...
886         0       2    1      0      0  13.0000
887         1       1    0      0      0  30.0000
888         0       3    0      1      2  23.4500
889         1       1    1      0      0  30.0000
890         0       3    1      0      0   7.7500

[891 rows x 6 columns]

In [34]:
data.skew()

Survived    0.478523
Pclass     -0.630548
Sex        -0.618921
SibSp       3.695352
Parch       2.749117
Fare        4.787317
dtype: float64

In [35]:

#treating using log
import numpy as np
for col in data.columns:
    if data.skew().loc[col]>0.55:
        data[col]=np.log1p(data[col])
data.skew()

Survived    0.478523
Pclass     -0.630548
Sex        -0.618921
SibSp       1.661245
Parch       1.675439
Fare        0.394928
dtype: float64

In [36]:
df_x= data.drop(columns=["Sex"])

In [37]:
df_x

Survived  Pclass     SibSp     Parch      Fare
0           0       3  0.693147  0.000000  2.110213
1           1       1  0.693147  0.000000  4.280593
2           1       3  0.000000  0.000000  2.188856
3           1       1  0.693147  0.000000  3.990834
4           0       3  0.000000  0.000000  2.202765
..        ...     ...       ...       ...       ...
886         0       2  0.000000  0.000000  2.639057
887         1       1  0.000000  0.000000  3.433987
888         0       3  0.693147  1.098612  3.196630
889         1       1  0.000000  0.000000  3.433987
890         0       3  0.000000  0.000000  2.169054

[891 rows x 5 columns]

In [38]:
y= data["Sex"]

In [39]:
y

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int32

In [42]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
x=sc.fit_transform(df_x)
x=pd.DataFrame(x,columns=df_x.columns)

In [44]:
x

Survived  Pclass     SibSp     Parch      Fare
0         0.0     1.0  0.315465  0.000000  0.338125
1         1.0     0.0  0.315465  0.000000  0.685892
2         1.0     1.0  0.000000  0.000000  0.350727
3         1.0     0.0  0.315465  0.000000  0.639463
4         0.0     1.0  0.000000  0.000000  0.352955
..        ...     ...       ...       ...       ...
886       0.0     0.5  0.000000  0.000000  0.422864
887       1.0     0.0  0.000000  0.000000  0.550238
888       0.0     1.0  0.315465  0.564575  0.512205
889       1.0     0.0  0.000000  0.000000  0.550238
890       0.0     1.0  0.000000  0.000000  0.347554

[891 rows x 5 columns]

In [50]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=43)

In [51]:
lr=LogisticRegression()

In [53]:
lr.fit(x_train,y_train)
lr.score(x_train,y_train)
predlr=lr.predict(x_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7208121827411168
[[ 42  19]
 [ 36 100]]
              precision    recall  f1-score   support

           0       0.54      0.69      0.60        61
           1       0.84      0.74      0.78       136

    accuracy                           0.72       197
   macro avg       0.69      0.71      0.69       197
weighted avg       0.75      0.72      0.73       197



In [54]:
gnb= GaussianNB()
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

0.7157360406091371
[[46 15]
 [41 95]]
              precision    recall  f1-score   support

           0       0.53      0.75      0.62        61
           1       0.86      0.70      0.77       136

    accuracy                           0.72       197
   macro avg       0.70      0.73      0.70       197
weighted avg       0.76      0.72      0.73       197



In [55]:
model=[LogisticRegression(),GaussianNB(),DecisionTreeClassifier()]

In [56]:
for m in model:
    m.fit(x_train,y_train)
    m.score(x_train,y_train)
    predm=m.predict(x_test)
    print('Accuracy score of',m,'is')
    print(accuracy_score(y_test,predm))
    print(confusion_matrix(y_test,predm))
    print(classification_report(y_test,predm))
    print('\n')

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy score of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False) is
0.7208121827411168
[[ 42  19]
 [ 36 100]]
              precision    recall  f1-score   support

           0       0.54      0.69      0.60        61
           1       0.84      0.74      0.78       136

    accuracy                           0.72       197
   macro avg       0.69      0.71      0.69       197
weighted avg       0.75      0.72      0.73       197



Accuracy score of GaussianNB(priors=None, var_smoothing=1e-09) is
0.7157360406091371
[[46 15]
 [41 95]]
              precision    recall  f1-score   support

           0       0.53      0.75      0.62        61
           1       0.86      0.70      0.77       136

    accuracy   

In [58]:
from sklearn.model_selection import cross_val_score

gnbscores = cross_val_score(gnb,x,y,cv=5)
print(gnbscores)
print(gnbscores.mean(),gnbscores.std())

[0.69273743 0.77094972 0.76404494 0.76404494 0.79096045]
0.756547498091168 0.03339408200184109


In [61]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_train,y_train)
preddt=dt.predict(x_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))

0.751269035532995
[[ 42  19]
 [ 30 106]]
              precision    recall  f1-score   support

           0       0.58      0.69      0.63        61
           1       0.85      0.78      0.81       136

    accuracy                           0.75       197
   macro avg       0.72      0.73      0.72       197
weighted avg       0.77      0.75      0.76       197



In [62]:
from sklearn.model_selection import cross_val_score

dtscores = cross_val_score(dt,x,y,cv=5)
print(dtscores)
print(dtscores.mean(),dtscores.std())

[0.73743017 0.77094972 0.82022472 0.78089888 0.8079096 ]
0.7834826176587096 0.029090332029454585


In [63]:
from sklearn.model_selection import cross_val_score

lrscores = cross_val_score(lr,x,y,cv=5)
print(lrscores)
print(lrscores.mean(),lrscores.std())

[0.80446927 0.7877095  0.76966292 0.75842697 0.79661017]
0.783375765616339 0.01702557750067586


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence t

In [64]:
svc=SVC()

In [66]:
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))

0.751269035532995
[[ 42  19]
 [ 30 106]]
              precision    recall  f1-score   support

           0       0.58      0.69      0.63        61
           1       0.85      0.78      0.81       136

    accuracy                           0.75       197
   macro avg       0.72      0.73      0.72       197
weighted avg       0.77      0.75      0.76       197



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [67]:
from sklearn.model_selection import cross_val_score

svcscores = cross_val_score(svc,x,y,cv=5)
print(svcscores)
print(svcscores.mean(),svcscores.std())

[0.81005587 0.79888268 0.76966292 0.75842697 0.79661017]
0.7867277209236017 0.019399733524896


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

In [69]:

from sklearn.externals import joblib
joblib.dump(dt,'df_new.pkl')

['df_new.pkl']